const enName = {
  '透明塑膠袋': 'Transparent Plastic Bag',
  '髒髒塑膠袋': 'Dirty Plastic Bag',
  '安全帽': 'Helmet',
  '塑膠飲料杯': 'Plastic Drink Cup',
  '紙飲料杯': 'Paper Drink Cup',
  '保麗龍飲料杯': 'Styrofoam Drink Cup',
  '紙便當盒': 'Bento Box',
  '電子發票': 'Paper Receipt',
  '袋裝洋芋片': 'Chips Bag',
  '橡皮筋': 'Rubber Ban',
  '罐裝洋芋片': 'Chips Can',
  '披薩盒': 'Pizza Box',
  '輕便雨衣': 'Rain Poncho',
  '瓷器': 'Porcelain',
  '手提紙袋': 'Paper Bag',
  '梳子': 'Comb',
  '沐浴乳瓶罐': 'Shampoo',
  '醫療口罩': 'Face Mask',
  '網購破壞袋': 'ECommerce Delivery Bag',
  '生廚餘': 'Compostable Food Waste',
  '熟廚餘': 'Non-Compostable Food Waste',
  '塑膠湯匙': 'Plastic Spoon',
  '透明雞蛋盒': 'Plastic Egg Tray',
  '原子筆': 'Pen',
  '絨毛玩偶': 'Stuffed Toys',
  '洗面乳': 'Facial Cleanser',
  '產品外包裝': 'Product Package',
  '洋蔥網袋': 'Onion Reticule',
  '充電線': 'Charging Cable',
  '盆栽': 'Potted Plant',
  '養樂多': 'Yakult',
  '廣告傳單': 'Flyer',
  '薄塑膠盒': 'Plastic Carton',
  '木材、木頭家具': 'Wooden Chair',
  '塑膠餐盒': 'Plastic Bento Box',
  '奶油球': 'Creamer',
  '菸盒': 'Cigarette Box',
  '瑜珈墊': 'Yoga Mat',
  '馬桶刷': 'Toilet Brush',
  '紙尿布': 'Diaper',
  '水果網套': 'Fruit Cushion',
  '牛奶盒': 'Milk Carton',
  '免洗筷': 'Disposable Chopsticks',
  '濾水器濾芯': 'Filter Cartridge',
  '耳機': 'Earphones',
  '手機殼': 'Cellphone Case',
  '優格杯': 'Yogurt Cup',
  '鏡子': 'Mirror',
  '氣泡紙': 'Bubble Wrap',
  '枯枝落葉': 'Leaf',
  '口紅': 'Lipstick',
  '碎紙': 'Shredded Paper',
  '衣架': 'Hanger',
  '鉛筆': 'Pencil',
  '報紙': 'Newspaper',
  '熱咖啡杯': 'Hot Coffee Cup',
  '補充包': 'Refillpack',
  '小吃紙袋': 'Snack Paper Bag',
  '鋁箔紙': 'Aluminum Foil',
  '棉被枕頭': 'Quilt & Pillow',
  '塑膠吸管': 'Plastic Straw',
  '藥丸': 'Expired Medicines',
  '泡麵碗': 'Instant Noodle Bowl',
  '玻璃瓶': 'Glass Bottle',
  '立可帶': 'Correction Tape',
  '玩具': 'Plastic Toy',
  '釘書針': 'Staple',
  '膠囊咖啡': 'Used Capsule Coffee',
  '棉花棒': 'Cotton Swab',
  '打火機': 'Lighter',
  '碎玻璃': 'Broken Glass',
  '衛生紙包裝': 'Tissue Paper Package',
  '奶粉罐': 'Milk Powder Can',
  '隱形眼鏡': 'Contact Lens',
  '網購紙箱': 'ECommerce cartons',
  '光碟': 'CD',
  '鋁箔包': 'Beverage Carton',
  '拖把': 'Mop',
  '不織布提袋': 'Non-Woven Bag',
  '旅行行李箱': 'Travel Suitcase',
  '牙膏': 'Toothpaste',
  '信用卡': 'Credit Card',
  '彩色筆': 'Color Pen',
  '滑鼠': 'Mouse',
  '夾腳拖': 'Flip Flops',
  '雨傘': 'Umbrella',
  '塑膠牙線棒': 'Plastic Floss Stick',
  '鋁罐': 'Aluminum Can',
  '保鮮膜': 'Food Wrap',
  '油漆桶': 'Paint Bucket',
  '生鮮托盤': 'Fresh Food Tray',
  '寶特瓶': 'PET Bottle',
  '帳單信封': 'Bill Envelope',
  '牙刷': 'Toothbrush',
  '保養品瓶罐': 'Skin Care Products',
  '高壓瓶': 'High Pressure Can',
  '餅乾禮盒': 'Biscuit Gift Box',
  '衣服': 'Clothes',
  '環保袋': 'Reusable Bag',
  '鞋': 'Shoes',
  '泡棉': 'EPE Cushion',
}

export default enName
