module.exports = {
    '雨傘': require('./10 雨傘/index.png'),
'棉被枕頭': require('./101 棉被枕頭/index.png'),
'帳單信封': require('./115 帳單信封/index.png'),
'夾腳拖': require('./12 夾腳拖/index.png'),
'口紅': require('./122 口紅/index.png'),
'棉花棒': require('./124 棉花棒/index.png'),
'鋁罐': require('./13 鋁罐/index.png'),
'輕便雨衣': require('./135 輕便雨衣/index.png'),
'玻璃瓶': require('./14 玻璃瓶/index.png'),
'網購紙箱': require('./16 網購紙箱/index.png'),
'寶特瓶': require('./18 寶特瓶/index.png'),
'衣架': require('./19 衣架/index.png'),
'生鮮托盤': require('./20 生鮮托盤/index.png'),
'塑膠吸管': require('./23 塑膠吸管/index.png'),
'鏡子': require('./24 鏡子/index.png'),
'泡泡紙': require('./25 泡泡紙/index.png'),
'報紙': require('./27 報紙/index.png'),
'手提紙袋': require('./28 手提紙袋/index.png'),
'三角飯糰包裝': require('./3 三角飯糰包裝/index.png'),
'塑膠湯匙': require('./31 塑膠湯匙/index.png'),
'盆栽': require('./32 盆栽/index.png'),
'沐浴乳瓶罐': require('./33 沐浴乳瓶罐/index.png'),
'洗面乳': require('./34 洗面乳/index.png'),
'濾水器濾芯': require('./35 濾水器濾芯/index.png'),
'免洗筷': require('./37 免洗筷/index.png'),
'優格杯': require('./38 優格杯/index.png'),
'小吃紙袋': require('./39 小吃紙袋/index.png'),
'烤蛋白餐盒': require('./4 烤蛋白餐盒/index.png'),
'信用卡': require('./41 信用卡/index.png'),
'披薩盒': require('./42 披薩盒/index.png'),
'水果網套': require('./44 水果網套/index.png'),
'奶粉罐': require('./45 奶粉罐/index.png'),
'打火機': require('./46 打火機/index.png'),
'菸盒': require('./47 菸盒/index.png'),
'茶葉蛋殼加塑膠袋': require('./5 茶葉蛋殼加塑膠袋/index.png'),
'紙尿布': require('./51 紙尿布/index.png'),
'馬桶刷': require('./55 馬桶刷/index.png'),
'原子筆': require('./57 原子筆/index.png'),
'鉛筆': require('./58 鉛筆/index.png'),
'牙刷': require('./59 牙刷/index.png'),
'包子紙': require('./6 包子紙/index.png'),
'牙膏': require('./60 牙膏/index.png'),
'透明雞蛋盒': require('./61 透明雞蛋盒/index.png'),
'罐裝洋芋片': require('./64 罐裝洋芋片/index.png'),
'袋裝洋芋片': require('./65 袋裝洋芋片/index.png'),
'保養品瓶罐': require('./66 保養品瓶罐/index.png'),
'電子發票': require('./67 電子發票/index.png'),
'藥丸': require('./69 藥丸/index.png'),
'涼麵盒': require('./7 涼麵盒/index.png'),
'隱形眼鏡': require('./71 隱形眼鏡/index.png'),
'玩具': require('./73 玩具/index.png'),
'鋁箔包': require('./74 鋁箔包/index.png'),
'高壓瓶': require('./77 高壓瓶/index.png'),
'奶油球': require('./82 奶油球/index.png'),
'生滾皮蛋煲粥': require('./9 生滾皮蛋煲粥/index.png'),
'養樂多': require('./9 養樂多/index.png'),
'網購破壞袋': require('./90 網購破壞袋/index.png'),
'環保袋': require('./91 環保袋/index.png'),
'產品外包裝': require('./92 產品外包裝/index.png'),
'衣物': require('./95 衣物/index.png'),
'生廚餘': require('./96 生廚餘/index.png'),
'熟廚餘': require('./97 熟廚餘/index.png'),
...require('./single.png'),
'便當盒': require('./便當盒/index.png'),
'保鮮膜': require('./保鮮膜/index.png'),
'保麗龍飲料杯': require('./保麗龍飲料杯/index.png'),
'充電線%2F電源線': require('./充電線%2F電源線/index.png'),
'塑膠牙線棒': require('./塑膠牙線棒/index.png'),
'塑膠袋': require('./塑膠袋/index.png'),
'塑膠醬料盒': require('./塑膠醬料盒/index.png'),
'塑膠飲料底座%2F杯架': require('./塑膠飲料底座%2F杯架/index.png'),
'塑膠飲料杯': require('./塑膠飲料杯/index.png'),
'安全帽': require('./安全帽/index.png'),
'廣告傳單': require('./廣告傳單/index.png'),
'彩色筆': require('./彩色筆/index.png'),
'拖把': require('./拖把/index.png'),
'木片餐盒': require('./木片餐盒/index.png'),
'植物纖維餐盒': require('./植物纖維餐盒/index.png'),
'泡麵碗': require('./泡麵碗/index.png'),
'漢堡紙%2F三明治紙': require('./漢堡紙%2F三明治紙/index.png'),
'熱咖啡杯': require('./熱咖啡杯/index.png'),
'牛奶盒': require('./牛奶盒/index.png'),
'立可帶': require('./立可帶/index.png'),
'紙包裝盒': require('./紙包裝盒/index.png'),
'紙容器便當盒': require('./紙容器便當盒/index.png'),
'紙飲料杯': require('./紙飲料杯/index.png'),
'紙餐盒加蓋': require('./紙餐盒加蓋/index.png'),
'膠囊咖啡': require('./膠囊咖啡/index.png'),
'蔬菜塑膠袋': require('./蔬菜塑膠袋/index.png'),
'行李箱': require('./行李箱/index.png'),
'速食紙餐盒': require('./速食紙餐盒/index.png'),
'醫療口罩': require('./醫療口罩/index.png'),
'鋁箔餐盒': require('./鋁箔餐盒/index.png'),
'鋁製膠囊咖啡': require('./鋁製膠囊咖啡/index.png'),
'陶瓷碗盤': require('./陶瓷碗盤/index.png'),
'餅乾禮盒': require('./餅乾禮盒/index.png'),
  }