
    const path = require('path')
    module.exports = {
      '不織布提袋': { '不織布提袋': path.resolve(__dirname, './不織布提袋.png') },
'保鮮膜': { '保鮮膜': path.resolve(__dirname, './保鮮膜.png') },
'光碟': { '光碟': path.resolve(__dirname, './光碟.png') },
'單一材料TPE手機殼': { '單一材料TPE手機殼': path.resolve(__dirname, './單一材料TPE手機殼.png') },
'塑膠餐盒': { '塑膠餐盒': path.resolve(__dirname, './塑膠餐盒.png') },
'手機殼': { '手機殼': path.resolve(__dirname, './手機殼.png') },
'木材、木頭家具': { '木材、木頭家具': path.resolve(__dirname, './木材、木頭家具.png') },
'枯枝落葉': { '枯枝落葉': path.resolve(__dirname, './枯枝落葉.png') },
'梳子': { '梳子': path.resolve(__dirname, './梳子.png') },
'橡皮筋': { '橡皮筋': path.resolve(__dirname, './橡皮筋.png') },
'油漆桶': { '油漆桶': path.resolve(__dirname, './油漆桶.png') },
'洋蔥網袋': { '洋蔥網袋': path.resolve(__dirname, './洋蔥網袋.png') },
'滑鼠': { '滑鼠': path.resolve(__dirname, './滑鼠.png') },
'瑜珈墊': { '瑜珈墊': path.resolve(__dirname, './瑜珈墊.png') },
'碎玻璃': { '碎玻璃': path.resolve(__dirname, './碎玻璃.png') },
'碎紙': { '碎紙': path.resolve(__dirname, './碎紙.png') },
'絨毛玩偶': { '絨毛玩偶': path.resolve(__dirname, './絨毛玩偶.png') },
'耳機': { '耳機': path.resolve(__dirname, './耳機.png') },
'薄塑膠盒': { '薄塑膠盒': path.resolve(__dirname, './薄塑膠盒.png') },
'衛生紙包裝': { '衛生紙包裝': path.resolve(__dirname, './衛生紙包裝.png') },
'補充包': { '補充包': path.resolve(__dirname, './補充包.png') },
'釘書針': { '釘書針': path.resolve(__dirname, './釘書針.png') },
'鋁箔紙': { '鋁箔紙': path.resolve(__dirname, './鋁箔紙.png') },
'防撞乖乖粒': { '防撞乖乖粒': path.resolve(__dirname, './防撞乖乖粒.png') },
'鞋': { '鞋': path.resolve(__dirname, './鞋.png') },
'髒髒塑膠袋': { '髒髒塑膠袋': path.resolve(__dirname, './髒髒塑膠袋.png') },
    }
